language: java
dist: trusty
jdk:
  - oraclejdk9
  - oraclejdk8

script:
  - ./gradlew clean check
  - # gradlew aggregateJavadocs is failing with JDK9 with error "package javax.xml.bind is declared in module java.xml.bind, which is not in the module graph"
  - jdk_switcher use oraclejdk8
  - ./gradlew aggregateJavadocs


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/