name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '15' ] 
    name: Java ${{ matrix.Java }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and Test with Gradle
        run: ./gradlew clean test
      - name: Javadoc
        if: matrix.java == '8'
        run: ./gradlew build aggregateJavadocs
        
      - name: Upload Unit Test Results And Specification
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: reports-java-${{ matrix.java }}
          path: |
            cubano-*/build/test-results/**/*.xml

  publish-test-results:
    name: "Publish Test Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    # the build-and-test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
          
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/test-results/**/*.xml
